// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABackTop: typeof import('@arco-design/web-vue')['BackTop']
    AButton: typeof import('@arco-design/web-vue')['Button']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    AScrollbar: typeof import('@arco-design/web-vue')['Scrollbar']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    Empty: typeof import('./../components/Empty.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    LinkItem: typeof import('./../components/LinkItem.vue')['default']
    PageBanner: typeof import('./../components/PageBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
